name: player_exchange
description: Playser Exchange

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^0.23.0+1
  dio: ^4.0.4
  shared_preferences: ^2.0.13
#  sn_progress_dialog: ^1.0.3
  fluttertoast:
  fl_chart: ^0.40.2
  auto_size_text: ^3.0.0
  youtube_player_flutter: ^8.0.0
  http: ^0.13.3
  image_picker: ^0.8.5
  flutter_image_compress: ^1.0.0-nullsafety
#  video_player: ^2.1.0
  flutter_stripe: ^2.4.0
  paginated_search_bar: ^1.1.2
  cached_network_image: ^3.2.0
#  nb_utils: ^4.6.1
  webview_flutter: ^3.0.4
  time_elapsed: ^0.2.6
#  syncfusion_flutter_pdfviewer: ^20.2.39-beta
  flutter_pdfview: ^1.2.1
  flutter_cached_pdfview: ^0.4.1
  firebase_core: ^1.21.1
  cloud_firestore: ^3.4.6
  firebase_storage: ^10.3.7
  flutter_datetime_picker: ^1.5.1
  firebase_messaging: ^11.4.0
  flutter_local_notifications: ^8.2.0
  provider: ^6.0.2
  intl: ^0.17.0
#  advance_pdf_viewer: any

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_name: "^0.0.1"
  flutter_launcher_icons: "^0.9.2"



  flutter_lints: ^1.0.0

#flutter_launcher_name:
#  name: "Player Exchange"
#  Commands to run after adding dependency
#  flutter pub get
#  flutter pub run flutter_launcher_name:main

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  #  Commands to run after adding dependency
#  flutter pub get
#  flutter pub run flutter_launcher_icons:main

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logo/
    - assets/tabs_icons/
    - assets/pdfs/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
