// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp2nnK27MfSVIqevl3xGseEmoi4iVUhEc',
    appId: '1:761797681586:web:deb932d3d941ff5f7404ab',
    messagingSenderId: '761797681586',
    projectId: 'player-exchange-ad78f',
    authDomain: 'player-exchange-ad78f.firebaseapp.com',
    storageBucket: 'player-exchange-ad78f.appspot.com',
    measurementId: 'G-EQ31F3H5RE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC_BWxNmCby2FdZ0PKlEfl48AwVP7SGAs',
    appId: '1:761797681586:android:44b0289d92c9bc427404ab',
    messagingSenderId: '761797681586',
    projectId: 'player-exchange-ad78f',
    storageBucket: 'player-exchange-ad78f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR_ofRzSAvqJSTMHUsCir5SUIwg8hk_dA',
    appId: '1:761797681586:ios:13593a9e24e9275c7404ab',
    messagingSenderId: '761797681586',
    projectId: 'player-exchange-ad78f',
    storageBucket: 'player-exchange-ad78f.appspot.com',
    iosClientId: '761797681586-5bm03kn1s9prgs5ffcuvmqko1gpu3ota.apps.googleusercontent.com',
    iosBundleId: 'com.codetivelab.playerexchange',
  );
}
